# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-CompileX-Tranport-SOAPXMPP
version:      0.6
version_from: lib/XML/CompileX/Transport/SOAPXMPP.pm
installdirs:  site
requires:
    AnyEvent:                      0
    Event:                         0
    Net::XMPP2:                    0
    XML::Compile::SOAP:            0.73

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
